### ISSUE TITLE
Don't find data in `bucc2017` and `dictionaries` folders

### ISSUE THREAD

**Issue by tienduccao** [zzcoolj/Parallel-Sentences-Identifier#1]
Because of the configuration in `.gitignore`, I couldn't find any data of `bucc2017` and `dictionaries` folders. Maybe you can provide a link or a script to download the data :)?

**Comment by zzcoolj** [comment]
Hi, thanks for your question and suggestion. 
data folder is just to show the data directory layout/structure.
And I've updated the README file, you could find the resources links and information in the Directory layout part now.
